name: called
on:
  workflow_call
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0
      - name: do-something
        run: |
          echo 'Hello!'
    

