name: testRE

on:
    push:
        branches: [ '*' ]
        tags: [ 'v[0-9]+\.[0-9]+\.[0-9]+' ]

jobs:
    validate:
        runs-on: ubuntu
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: test
              run: |
                git status
